### ISSUE TITLE
Nav in password reset

### ISSUE THREAD

**Issue by Strider2** [FatihKoz/DisposableTheme#10]
It might be an idea to include the nav when you go to forget password page, as there is no quick way back to the homepage from there.

**Comment by FatihKoz** [comment]
You can just set this `disable_nav` to `false` in your duplicated theme blade. Same logic applies to login too.

https://github.com/FatihKoz/DisposableTheme/blob/753170afa13ad2c1ac711c371cb112a8525b8547/resources/views/layouts/Disposable_v3/auth/passwords/reset.blade.php#L1
