### ISSUE TITLE
Slight menu issue

### ISSUE THREAD

**Issue by FroztIkon** [FatihKoz/DisposableTheme#11]
Phpvms version:
7.0.0-beta.5+230828.61433c
Apache:
Apache version 2.4.52
Database:
MariaDB version 10.6.12
PHP:
PHP Version 8.1.23
Redis is supported by php

Browser:
Vivaldi
Chrome

The main menu on the top, shows up like this:
disposable.menu_roster
disposable.menu_reports
disposable.menu_mapflt

Site:
vms.uavirtual.org

**Comment by FatihKoz** [comment]
![image](https://github.com/FatihKoz/DisposableTheme/assets/74361521/ce09034f-a75b-436d-8422-56ad4a74a233)

Looks like you are missing the language files of the theme on your install... Please double check your `resources/lang/en` folder for existence of `disposable.php`. Readme explains the logic in non-standard manual installation steps.
