### ISSUE TITLE
Home Airport Empty - Register View

### ISSUE THREAD

**Issue by edgardoalvarez100** [FatihKoz/DisposableTheme#13]
In the registration view it is not showing the list of airports for home, with the last update it does not work

![image](https://github.com/FatihKoz/DisposableTheme/assets/446122/ef3127b0-3fdc-499c-9a29-a39fb29341b4)

![image](https://github.com/FatihKoz/DisposableTheme/assets/446122/f5b8695a-d899-4838-892c-d1933e81e020)

![image](https://github.com/FatihKoz/DisposableTheme/assets/446122/c2de1cc7-4ea8-44fa-8ac4-14112414350b)

**Comment by FatihKoz** [comment]
Did you updated your theme, specially your duplicated app.blade ?

**Comment by FatihKoz** [comment]
Latest theme version is compatible with beta.5 and further/newer versions, so you must have both your phpvms and themes (including any custom duplicates) updated.

**Comment by edgardoalvarez100** [comment]
> Did you updated your theme, specially your duplicated app.blade ?

thanks, working now
