### ISSUE TITLE
Missing classes in /resources/views/layouts/Disposable_v3/nav_menu.blade.php

### ISSUE THREAD

**Issue by jonbeckett** [FatihKoz/DisposableTheme#17]
Lines 337 and 345 - the LI tags are missing  `class="nav-item"`

**Comment by FatihKoz** [comment]
You mean these?

https://github.com/FatihKoz/DisposableTheme/blob/76cc8980cf7bacb600152c0e553374b5d2e97c7d/resources/views/layouts/Disposable_v3/nav_menu.blade.php#L336-L352

Even though they will act normally (as designed) with the `nav-link` class assigned to the links, no problem we can fix it before next release :)
