### ISSUE TITLE
Typo in the register view

### ISSUE THREAD

**Issue by jonbeckett** [FatihKoz/DisposableTheme#18]
In the register view, you have a typo in the form HTML element - "methot" instead of "method" - which prevents anybody from registering :)

**Comment by FatihKoz** [comment]
Did you checked the last commit and release ?

Sent from mobile device / Mobil cihaz ile gönderildi

22 Şub 2024 Per 15:15 tarihinde Jonathan Beckett ***@***.***>
şunu yazdı:
